### ISSUE TITLE
SVG download

### ISSUE THREAD

**Issue by just-jason** [jasonwebb/2d-differential-growth-experiments#10]
HI Jason,
I have loved watching the GitHub.io deomos, and would like to try and plot a few of the examples. When I down load the SVG ( press s) the SVG seems to have an error and can not be opened in either Inkscape nor fusion. Is there something I need to do differently when downloading the SVG ?
[differential-growth-1587315052808.zip](https://github.com/jasonwebb/2d-differential-growth-experiments/files/4499789/differential-growth-1587315052808.zip)

**Comment by jasonwebb** [comment]
Hey there! I just updated the SVG export code - give it another shot on any of the sketches and let me know if its working (don't forget to clear your cache, just to be safe)!

**Comment by just-jason** [comment]
Perfect!
