### ISSUE TITLE
Unminified files?

### ISSUE THREAD

**Issue by molecule** [jasonwebb/2d-differential-growth-experiments#8]
Hello! Just curious if it would be possible to release an un-minified version of any of these? I'm trying to port some of this to processing but it's super tough to parse in the current format. 

https://github.com/jasonwebb/2d-differential-growth-experiments/blob/master/01%20-%20single%20line/dist/app.min.js

Thanks! Beautiful work :)

**Comment by jasonwebb** [comment]
Yep! All the source files are contained within this very repo! There are folders containing the source for each experiment (like "01 - single line"), each with a single p5js sketch in their respective `entry.js` files. Inside of those files you'll see references to some common custom modules that are all stored in the `./core` folder.

The p5js sketches are all really simple, and are really just "controllers" for the core code - configuring it and running it in different ways to get different results. I'm going to bet that the [Path](https://github.com/jasonwebb/2d-differential-growth-experiments/blob/master/core/Path.js) module will be most relevant to what you're looking to do :)

**Comment by molecule** [comment]
Ah thanks! That clarifies things. Apologies: I'm definitely not overly familiar with Javascript projects, so was looking in the wrong spot.

Appreciate it!
