### ISSUE TITLE
Question: Could it also be used to shrink a form until we get just the center line?

### ISSUE THREAD

**Issue by schittli** [jasonwebb/2d-differential-growth-experiments#9]
**Thank you very much for sharing this great library!,**
it is always very impressive when mathematics and computer science become visible.

Your software gave me an idea:
It's strange that we still have the unresolved computer science problem to 
**create a single stroke font from an outline font**:

![Outline Font to Single Line, Stroke Font](https://user-images.githubusercontent.com/8282673/66474140-f9e16800-ea90-11e9-84e8-083b53be8477.png)

#### Therefore I have this question:
Would it be possible to use your software to shrink an outline until only one line remains?

Thanks a lot for any answer.
Kind regards,
Thomas

**Comment by msurguy** [comment]
@schittli I believe what you're looking for is something like this: https://github.com/FlorisSteenkamp/MAT 
Also, I'm working a lot on using Hershey fonts in the browser. Stay tuned for some developments :)

**Comment by jasonwebb** [comment]
@msurguy beat me to it! 

Differential growth is inherently about _growing_ shapes, not simplifying or reducing them. I agree that the medial axis transform is probably what you want. Here are a couple of sources to get you started: https://github.com/jasonwebb/morphogenesis-resources#medial-axis

**Comment by schittli** [comment]
Thank you very much, @jasonwebb and @msurguy for your answer and help!
I'm going to study your proposals.
